// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCligX0-EQn6JC1xri1eJVOlB2pqKfi09I',
    appId: '1:1044976890874:web:bfb1a5b64684e04b802a43',
    messagingSenderId: '1044976890874',
    projectId: 'tourhub-1aade',
    authDomain: 'tourhub-1aade.firebaseapp.com',
    storageBucket: 'tourhub-1aade.firebasestorage.app',
    measurementId: 'G-VLCL5HYBWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxeSLh1dYS4YPIvj3wg4B3efeHZPAw6RQ',
    appId: '1:1044976890874:android:e3e3a921ced48d40802a43',
    messagingSenderId: '1044976890874',
    projectId: 'tourhub-1aade',
    storageBucket: 'tourhub-1aade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPlOwbtQJtOnrU7Y5px_GAMdZO8O-9Co',
    appId: '1:1044976890874:ios:d099e15f5580d6f5802a43',
    messagingSenderId: '1044976890874',
    projectId: 'tourhub-1aade',
    storageBucket: 'tourhub-1aade.firebasestorage.app',
    iosBundleId: 'com.example.tourhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOPlOwbtQJtOnrU7Y5px_GAMdZO8O-9Co',
    appId: '1:1044976890874:ios:d099e15f5580d6f5802a43',
    messagingSenderId: '1044976890874',
    projectId: 'tourhub-1aade',
    storageBucket: 'tourhub-1aade.firebasestorage.app',
    iosBundleId: 'com.example.tourhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCligX0-EQn6JC1xri1eJVOlB2pqKfi09I',
    appId: '1:1044976890874:web:862d59c906a4e918802a43',
    messagingSenderId: '1044976890874',
    projectId: 'tourhub-1aade',
    authDomain: 'tourhub-1aade.firebaseapp.com',
    storageBucket: 'tourhub-1aade.firebasestorage.app',
    measurementId: 'G-H0SFH2W8V1',
  );
}
